import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createTestingReport } from '../lib/testing-report';
import { formalDimensions } from '../lib/formal-dimensions';
import { createCounselorPackage, counselorPackageMarkdown, artifactFilename, hasCompleteDimensionResults } from '../lib/counselor-package';
import { studentReportMarkdown } from '../lib/student-report-markdown';
import { counselorPromptTemplate } from '../prompts/counselor-analysis-v3';

const data = createTestingReport();
assert.equal(data.source.mode, 'testing');
assert.equal(data.source.scoringVersion, 'ui-fixture-only-not-scored');
assert.deepEqual(data.dimensionResults!.map(d => d.name), formalDimensions.map(d => d.name));
assert.equal(data.dimensionResults!.flatMap(d => d.subdimensions).length, 36);
assert.equal(data.preferenceResults.length, 4);
assert.equal(data.developmentProfile!.clues.length >= 2 && data.developmentProfile!.clues.length <= 4, true);
assert.equal(data.developmentProfile!.explorationQuestions.length >= 2 && data.developmentProfile!.explorationQuestions.length <= 4, true);
assert.equal(hasCompleteDimensionResults(data), true);
const packageData = createCounselorPackage(data);
assert.strictEqual(packageData.assessment.dimensionResults, data.dimensionResults);
assert.strictEqual(packageData.assessment.developmentProfile, data.developmentProfile);
assert.strictEqual(packageData.assessment.responses, data.rawAnswers);
assert.equal(packageData.educationPreferences.targetRegions, '美国、英国、香港');
assert.equal(packageData.additionalContext, '目前IB课程，数学AA HL，最近一次预测分6。');
const undecided = createCounselorPackage({ ...data, studentContext: { ...data.studentContext, targetRegions: '还没确定', additionalContext: '' } });
assert.equal(undecided.educationPreferences.targetRegions, '还没确定');
assert.equal(undecided.additionalContext, '');
const markdown = counselorPackageMarkdown(packageData);
assert.ok(markdown.includes('PART A — Student Development Context'));
assert.ok(markdown.includes('PART B — Counselor Analysis Instructions'));
assert.ok(!markdown.includes('{{STUDENT_DEVELOPMENT_CONTEXT}}'));
assert.ok(!markdown.includes('家长'));
assert.ok(markdown.includes('未经核实'));
assert.ok(markdown.includes('美国、英国、香港'));
assert.ok(markdown.includes('目前IB课程，数学AA HL，最近一次预测分6。'));
assert.ok(!JSON.stringify(packageData).match(/parent|dualPerspective/i));
const original = readFileSync('../docs/counselor-prompt-v3-provided.txt', 'utf8');
assert.equal(counselorPromptTemplate, original.replace('高中生\n+\n家长\n+\n升学指导师', '高中生\n+\n升学指导师'));
const studentMarkdown = studentReportMarkdown(data);
for (const title of ['01｜我的发展画像','02｜比较明显的发展线索','03｜真实经历中的我','04｜测评和真实经历放在一起','05｜值得继续认识的问题','06｜下一步']) assert.ok(studentMarkdown.includes(title));
assert.ok(!studentMarkdown.includes('Counselor Analysis Instructions'));
assert.ok(studentMarkdown.includes('美国、英国、香港'));
assert.ok(studentMarkdown.includes('学生主动补充的信息（未经核实）'));
assert.ok(studentMarkdown.includes('目前IB课程，数学AA HL，最近一次预测分6。'));
assert.notEqual(studentMarkdown, markdown);
for (const changes of [{dimensionResults:null}, {preferenceResults:[]}, {developmentProfile:null}, {rawAnswers:[]}, {counselorPackageStatus:'not_ready' as const}]) {
  assert.throws(() => createCounselorPackage({...data,...changes}));
}
assert.equal(artifactFilename('counselor',''), '导师分析资料.md');
assert.equal(artifactFilename('counselor','小雨'), '导师分析资料_小雨.md');
console.log('PASS: official dimension names, 36 subdimensions, 4 bipolar preferences, 6 report sections, shared structured data, missing-result gate, V3 fidelity, separate Markdown exports, no parent fields');
